apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana       # Name of the chart
      version: 8.6.0           # Specific version of the chart
      sourceRef:
        kind: HelmRepository
        name: grafana-helm-repo
        namespace: grafana
  values:
    replicaCount: 1            # Example: Set the number of replicas
    service:
      type: LoadBalancer         # Example: Use LoadBalancer for external access
    metrics:
      enabled: true              # Example: Enable Prometheus metrics
  valuesFrom:
    - kind: ConfigMap
      name: grafana-values   
