apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - influxdb-acr-secret.yaml
  - influxdb-values-configmap.yaml
  - helmrepository.yaml
  - helmrelease.yaml

namespace: influxdb
