apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-acr-secret.yaml
  - grafana-values-configmap.yaml
  - helmrepository.yaml
  - helmrelease.yaml

namespace: grafana
