apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 1m
  chart:
    spec:
      chart: postgresql       # Name of the chart
      version: 2.27.0          # Specific version of the chart
      sourceRef:
        kind: HelmRepository
        name: postgresql-helm-repo
        namespace: postgresql
  values:
    replicaCount: 1            # Example: Set the number of replicas
    service:
      type: LoadBalancer         # Example: Use LoadBalancer for external access
    metrics:
      enabled: true              # Example: Enable Prometheus metrics
  valuesFrom:
    - kind: ConfigMap
      name: postgresql-values   
