apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgresql-helm-repo
  namespace: postgresql
spec:
  interval: 1m
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci
  
