apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql-acr-secret.yaml
  - postgresql-values-configmap.yaml
  - helmrepository.yaml
  - helmrelease.yaml

namespace: postgresql
